@startuml
class Platform{
- String platformName
- ArrayList<Client> clients
- ArrayList<Server> servers
}

class Server{
- String serverName
- ArrayList<Client> clients
- ArrayList<Chatroom> chatrooms
}

class Client{
- String id
- String username
- String password
- HashMap<Client, Message> privateMessages
- ArrayList<Server> servers
- boolean online
- ArrayList<Client> friends
- ArrayList<Client> blockedAccounts
- String IP
}

class Chatroom{
- String name
- ArrayList<Client> clients
- ArrayList<Message> messages
}

class Message{
- Client sender
- Client receiver
- String message
- Date date/time
- String IP
- String location
}

package util{
class GUI
class API
class Encrypting{
+ String encrypt(String message)
+ String decrypt(String message)
}
database "Database"{
}

Platform *-- Server
Platform *-- Client
Platform *-- GUI
Platform --* "Database"

Client *-- Message
Client --* "Database"

Server *-- Chatroom
Server --* "Database"

Chatroom *-- Message
Chatroom *-- API
Chatroom --* "Database"

Message *-- Encrypting
Message --* "Database"

}



@enduml